# Generated by Django 4.2.7 on 2024-03-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_banner', models.FileField(upload_to='img/mainpage')),
                ('main_banner_link', models.CharField(blank=True, max_length=125, null=True)),
                ('main_gif', models.FileField(upload_to='img/mainpage')),
                ('main_gif_link', models.CharField(blank=True, max_length=125, null=True)),
                ('X_link', models.CharField(blank=True, max_length=125, null=True)),
                ('Aparat_link', models.CharField(blank=True, max_length=125, null=True)),
                ('IG_link', models.CharField(blank=True, max_length=125, null=True)),
                ('Phone_no', models.CharField(blank=True, max_length=125, null=True)),
            ],
        ),
    ]
