# Generated by Django 4.2.7 on 2024-03-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_main_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_page',
            name='ad_1',
            field=models.FileField(blank=True, null=True, upload_to='img/mainpage'),
        ),
        migrations.AddField(
            model_name='main_page',
            name='ad_1_link',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='main_page',
            name='ad_2',
            field=models.FileField(blank=True, null=True, upload_to='img/mainpage'),
        ),
        migrations.AddField(
            model_name='main_page',
            name='ad_2_link',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
