# Generated by Django 4.2.7 on 2024-03-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_main_page_ad_1_main_page_ad_1_link_main_page_ad_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Large_banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.FileField(upload_to='img/mainpage')),
            ],
        ),
    ]
