# Generated by Django 4.2.7 on 2024-03-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_large_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='large_banner',
            name='link',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
