# Generated by Django 4.2.7 on 2024-03-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_large_banner_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_fa', models.CharField(max_length=40)),
                ('color_en', models.CharField(max_length=40)),
                ('color_tag', models.CharField(max_length=9)),
            ],
        ),
    ]
