# Generated by Django 4.2.7 on 2024-03-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.ManyToManyField(to='main.colors'),
        ),
    ]
