# Generated by Django 4.2.7 on 2024-03-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_item_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to='img/items'),
        ),
        migrations.AddField(
            model_name='item',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to='img/items'),
        ),
        migrations.AddField(
            model_name='item',
            name='image4',
            field=models.FileField(blank=True, null=True, upload_to='img/items'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FileField(upload_to='img/items'),
        ),
    ]
