# Generated by Django 4.2.7 on 2024-03-16 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_item_image2_item_image3_item_image4_alter_item_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='image',
            new_name='image1',
        ),
    ]
